version: '3.8'

services:

  docker-mysql:
    container_name: docker-mysql
    image: mysql:5.6.47
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dollar_trading
      MYSQL_USER: gleb
      MYSQL_PASSWORD: gleb
    ports:
      - "3306:3306"

  myapp:
    container_name: final-app2
    image: mysql-app-rabbit
    restart: always
    links:
      - "docker-mysql"
    environment:
      spring.rabbitmq.host: rabbitmq-2
    ports:
      - "9000:8090"

  rabbitMQ:
    container_name: rabbitmq-2
    image: rabbitmq:3.9-management
    restart: always
    links:
      - "localhost"
    ports:
      - "5672:5672"
      - "15672:15672"
